mfa/urls.py
from django.urls import path

from .decorators import public
from .views import MFAAuthView
from .views import MFACreateView
from .views import MFADeleteView
from .views import MFAListView

app_name = 'mfa'
urlpatterns = [
    path('', public(MFAListView.as_view()), name='list'),
    path('<int:pk>/delete/', public(MFADeleteView.as_view()), name='delete'),
    path('create/<method>/', public(MFACreateView.as_view()), name='create'),
    path('auth/<method>/', MFAAuthView.as_view(), name='auth'),
]

mfa/models.py
from django.conf import settings
from django.db import models


class MFAKey(models.Model):
    id = models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    method = models.CharField(max_length=8, choices=[
        ('FIDO2', 'FIDO2'),
        ('TOTP', 'TOTP'),
        ('recovery', 'recovery'),
    ])
    name = models.CharField(max_length=32)
    secret = models.TextField()
    # replay protection
    last_code = models.CharField(max_length=32, blank=True)

mfa/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class MFABaseForm(forms.Form):
    code = forms.CharField(label=_('Authentication code'))

    def __init__(self, validate_code=None, **kwargs):
        self.validate_code = validate_code
        super().__init__(**kwargs)
        self.fields['code'].widget.attrs.update({'autocomplete': 'one-time-code'})

    def clean(self):
        cleaned_data = super().clean()
        code = cleaned_data.get('code')
        if code:
            try:
                cleaned_data['secret'] = self.validate_code(code)
            except ValueError as e:
                raise forms.ValidationError(_('Validation failed')) from e
        return cleaned_data


class MFAAuthForm(MFABaseForm):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['code'].widget.attrs.update({'autofocus': True})


class MFACreateForm(MFABaseForm):
    name = forms.CharField(label=_('Name for this key'), max_length=32)

mfa/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth import user_login_failed
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView
from django.views.generic import ListView

from . import settings
from .decorators import login_not_required
from .decorators import stronghold_login_not_required
from .forms import MFAAuthForm
from .forms import MFACreateForm
from .mail import send_mail
from .mixins import MFAFormView
from .models import MFAKey


class LoginView(DjangoLoginView):
    def no_key_exists(self, form):
        return super().form_valid(form)

    def form_valid(self, form):
        user = form.get_user()
        if not user.mfakey_set.exists():
            return self.no_key_exists(form)

        self.request.session['mfa_user'] = {
            'pk': user.pk,
            'backend': user.backend,
        }
        self.request.session['mfa_success_url'] = self.get_success_url()
        for method in settings.METHODS:
            if user.mfakey_set.filter(method=method).exists():
                return redirect('mfa:auth', method)


class MFAListView(LoginRequiredMixin, ListView):
    model = MFAKey

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['max_keys'] = settings.MAX_KEYS_PER_ACCOUNT
        return context


class MFADeleteView(LoginRequiredMixin, DeleteView):
    model = MFAKey

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_success_url(self):
        return reverse('mfa:list')


class MFACreateView(LoginRequiredMixin, MFAFormView):
    form_class = MFACreateForm

    def get_template_names(self):
        return f'mfa/create_{self.method.name}.html'

    def get_success_url(self):
        return reverse('mfa:list')

    def begin(self):
        return self.method.register_begin(self.request.user)

    def complete(self, code):
        return self.method.register_complete(self.challenge[1], code)

    def form_valid(self, form):
        if settings.MAX_KEYS_PER_ACCOUNT:
            count = self.request.user.mfakey_set.count()
            if count >= settings.MAX_KEYS_PER_ACCOUNT:
                form.add_error(None, format_lazy(_(
                    'You cannot have more than {} keys. Please delete '
                    'one of your existing keys before adding a new one.'
                ), settings.MAX_KEYS_PER_ACCOUNT))
                return self.form_invalid(form)
        MFAKey.objects.create(
            user=self.request.user,
            method=self.method.name,
            name=form.cleaned_data['name'],
            secret=form.cleaned_data['secret'],
        )
        messages.success(self.request, _('Key was created successfully!'))
        return super().form_valid(form)


@method_decorator(login_not_required, name='dispatch')
@method_decorator(stronghold_login_not_required, name='dispatch')
class MFAAuthView(MFAFormView):
    form_class = MFAAuthForm

    def get_template_names(self):
        return f'mfa/auth_{self.method.name}.html'

    def get_success_url(self):
        success_url = self.request.session.pop('mfa_success_url')
        if self.method.name == 'recovery':
            return reverse('mfa:list')
        else:
            return success_url

    @cached_property
    def user(self):
        try:
            user_data = self.request.session['mfa_user']
        except KeyError as e:
            raise Http404 from e
        User = get_user_model()
        user = get_object_or_404(User, pk=user_data['pk'])
        user.backend = user_data['backend']
        return user

    def begin(self):
        return self.method.authenticate_begin(self.user)

    def complete(self, code):
        return self.method.authenticate_complete(
            self.challenge[1], self.user, code,
        )

    def form_invalid(self, form):
        user_login_failed.send(
            sender=__name__,
            credentials={'username': self.user.get_username()},
            request=self.request,
        )
        send_mail(self.user, self.method)
        return super().form_invalid(form)

    def form_valid(self, form):
        login(self.request, self.user)
        del self.request.session['mfa_user']
        return super().form_valid(form)

mfa/templates/mfa/auth_FIDO2.html
{% load static %}

<h1>Two-factor authentication</h1>
<p>When you are ready to authenticate with FIDO2, press the button below.</p>

<form data-fido2-auth="{{ mfa_data }}" method="POST">
    {% csrf_token %}
    {% for error in form.errors %}
        <p>{{ error }}</p>
    {% endfor %}
    {{ form.code.as_hidden }}
    <button autofocus>Verify</button>
    <a href="{% url 'mfa:auth' 'TOTP' %}">Use TOTP instead</a>
    <a href="{% url 'mfa:auth' 'recovery' %}">Use recovery code instead</a>
</form>

<script src="{% static 'mfa/fido2.js' %}" type="module"></script>

mfa/templates/mfa/auth_TOTP.html
{% extends "mfa/base.html" %}
{% load i18n static %}

{% block content_title %}
<h1>Two-factor authentication</h1>
{% endblock %}

{% block content_subtitle %}
<p>
    Open your TOTP app to get an authentication code
    {% for method in methods %}
    {% if method != 'TOTP' %}
    or <a href="{% url 'mfa:auth' method %}">use {{method}} instead</a>
    {% endif %}
    {% endfor %}.
</p>
{% endblock %}

{% block form %}
<form method="POST">
    {% csrf_token %}
    <div class="form-row">
        {{ form.code.errors }}
        <h2>{{ form.code.label }}:</h2>
        <p>{{ form.code }}</p>
    </div>
    <div class="submit-row">
        <input type="submit" value="{% translate 'Verify' %}">
        <input type="hidden" name="next" value="{{ next }}">
    </div>
</form>
{% endblock %}

mfa/templates/mfa/auth_recovery.html
{% extends "mfa/base.html" %}
{% load i18n static %}

{% block content_title %}
<h1>Two-factor authentication</h1>
{% endblock %}

{% block content_subtitle %}
<p>
    <strong>WARNING</strong>:
    The recovery code will be removed after it has been used.
    Make sure to create a new one after login!
    {% for method in methods %}
    {% if method != 'recovery' %}
    or <a href="{% url 'mfa:auth' method %}">use {{method}} instead</a>
    {% endif %}
    {% endfor %}.
</p>
{% endblock %}

{% block form %}
<form method="POST">
    {% csrf_token %}
    <div class="form-row">
        {{ form.code.errors }}
        <h2>{{ form.code.label }}:</h2>
        <p>{{ form.code }}</p>
    </div>
    <div class="submit-row">
        <input type="submit" value="{% translate 'Verify' %}">
        <input type="hidden" name="next" value="{{ next }}">
    </div>
</form>
{% endblock %}

mfa/templates/mfa/base.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static 'admin/css/login.css' %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login mfa{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content_title %}{% endblock %}

{% block nav-breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% block form %}
{% endblock %}

</div>
{% endblock %}

mfa/templates/mfa/create_FIDO2.html
{% load static %}

<p>You will be prompted to activate the device once you click "create".</p>

<form data-fido2-create="{{ mfa_data }}" method="POST">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <p>{{ error }}</p>
    {% endfor %}
    <label>
        {{ form.name.label }}
        {{ form.name }}
    </label>
    {{ form.code.as_hidden }}
    <button>Create</button>
</form>

<script src="{% static 'mfa/fido2.js' %}" type="module"></script>

mfa/templates/mfa/create_TOTP.html
{% load mfa %}

<p>Scan the code with your TOTP app and enter a valid code to finish registration.</p>

{{ mfa_data.url|qrcode }}
{{ mfa_data.secret }}

<form method="POST">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <p>{{ error }}</p>
    {% endfor %}
    <label>
        {{ form.name.label }}
        {{ form.name }}
    </label>
    <label>
        {{ form.code.label }}
        {{ form.code }}
    </label>
    <button>Create</button>
</form>

mfa/templates/mfa/create_recovery.html
{% load mfa %}

<p>A recovery code can be used when you lose access to your other two-factor authentication options. Each recovery code can only be used once.</p>
<p>Make sure to store it in a safe place! If you lose your login keys and don’t have the recovery codes you will lose access to your account.</p>

<form method="POST">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <p>{{ error }}</p>
    {% endfor %}
    <label>
        {{ form.name.label }}
        {{ form.name }}
    </label>
    <label>
        {{ form.code.label }}
        <input name="code" value="{{ mfa_data.code }}" readonly>
    </label>
    <label>
        <input type="checkbox" required>
        I have safely stored the code
    </label>
    <button>Create</button>
</form>

mfa/templates/mfa/mfakey_confirm_delete.html
{% extends "mfa/base.html" %}
{% load i18n static %}

{% block content_subtitle %}
<p>
    Are you sure you want to delete the key {{ object.name }}?
</p>
{% endblock %}

{% block form %}
<form method="POST">
    {% csrf_token %}
    <div class="submit-row">
        <input type="submit" value="{% translate 'Confirm' %}">
        <input type="hidden" name="next" value="{{ next }}">
    </div>
</form>
{% endblock %}

mfa/templates/mfa/mfakey_list.html
<h1>{% if object_list %}Login keys configured{% else %}No login keys configured{% endif %}</h1>
<p>Two-factor authentication adds an additional layer of security to your account by requiring more than just a password to log in.</p>

{% if object_list|length == 1 %}
    <p>
        <strong>WARNING</strong>:
        You have registered only a single key. If you lose access to that key you won't be able log into your account again.
        <a href="{% url 'mfa:create' 'recovery' %}">Create recovery code</a>
    </p>
{% endif %}

<ul>
    {% for key in object_list %}
        <li>
            {{ key.name }} ({{ key.method }})
            <a href="{% url 'mfa:delete' key.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>

{% if max_keys and user.mfakey_set.count >= max_keys %}
    <p>
        You cannot have more than {{ max_keys }} keys.
        Please delete one of your existing keys before adding a new one.
    </p>
{% else %}
    <a href="{% url 'mfa:create' 'TOTP' %}">Create TOTP key</a>
    <a href="{% url 'mfa:create' 'FIDO2' %}">Create FIDO2 key</a>
    <a href="{% url 'mfa:create' 'recovery' %}">Create recovery code</a>
{% endif %}